spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.h2.console.enabled=true
server.port=9007

spring.security.user.name=scastan
spring.security.user.password=caca