image: maven:3.9-eclipse-temurin-25

stages:
  - build-front
  - build-back

build-frontend:
  stage: build-front
  commands:
    - echo "Compil front-end... debut"
    - java -version
    - cd croussardsweb
    - mvn clean compile
    - echo "Compil front-end... fin"
  artifacts:
    paths:
      - croussardsweb/target/
    expire_in: 1 days

build-backend:
  stage: build-back
  commands:
    - echo "Compil back-end... debut"
    - java -version
    - cd croussardsapi
    - mvn clean compile
    - echo "Compil back-end... fin"
  artifacts:
    paths:
      - croussardsapi/target/
    expire_in: 1 days