image: maven:3.9-eclipse-temurin-25

stages:
  - build-back
  - test-back
  - deploy-back
  - build-front
  - test-front
  - deploy-front

build_backend:
  stage: build-back
  image: maven:3.9-eclipse-temurin-25
  variables:
    MAVEN_OPTS: "-Djava.net.preferIPv4Stack=true"
  script:
    - echo "Compil back-end... debut"
    - java -version
    - cd croussardsapi
    - mvn clean compile
  artifacts:
    paths:
      - croussardsapi/target/
    expire_in: 1 days

test-back:
  stage: test-back
  script:
    - echo "Test back"
    - cd croussardsapi
    - mvn test
  artifacts:
    paths:
      - croussardsapi/target/
    expire_in: 1 days

deploy-back:
  stage: deploy-back
  script:
    - echo "Deploy back"
    - cd croussardsapi
    - mvn deploy
  artifacts:
    paths:
      - croussardsapi/target/
    expire_in: 1 days

build-frontend:
  stage: build-front
  script:
    - echo "Compil front-end... debut"
    - java -version
    - cd croussardsweb
    - mvn clean compile
    - echo "Compil front-end... fin"
  artifacts:
    paths:
      - croussardsweb/target/
    expire_in: 1 days

test-front:
  stage: test-front
  script:
    - echo "Test front"
    - cd croussardsweb
    - mvn test
  artifacts:
    paths:
      - croussardsweb/target/
    expire_in: 1 days

deploy-front:
  stage: deploy-front
  script:
    - echo "Deploy front"
    - cd croussardsweb
    - mvn deploy
  artifacts:
    paths:
      - croussardsweb/target/
    expire_in: 1 days
